package rs.pupin.evmer.enums;

public enum HistoryEvent {
    BRISANJE,
    RESTOROVANJE,
    IZMENA_PODATAKA,
    DODVANJE_KALIBRACIJE,
    DODAVANJE,
    ZADUZENJE,
    RAZDUZENJE,
    PRIJAVA_KVARA,
    RESAVANJE_KVARA,
    REZERVISANJE,
    ISTEK_REZERVACIJE,
    OTKAZIVANJE_REZERVACIJE,
    ZAKAZIVANJE_KALIBRACIJE
}
